### ISSUE TITLE
Touble in install tha package

### ISSUE THREAD

**Issue by Dan-121** [daklab/LeafletSC#3]
Hi, thanks for developing such wonderful tools for us. Bot I have trouble in installing the packages. I'm looking forward to your conda install method.

Dan

**Comment by karini925** [comment]
Hi Dan, I am hoping to have a conda install method soon. In the meantime, I am happy to try and help debug any errors you are having!

**Comment by Dan-121** [comment]
Thank you for your great tool. I have been using it to analyze single-cell datasets generated by Drop-seq-like tools. However, I encountered an issue when using regtools to analyze the data. I received a warning stating "No CB tag found for alignment."

I suspected this might be due to the barcode, so I modified the file junctions_extractor.h in regtools, changing the CB tag to CR. Despite this change, the warning still occurs.

Could you please advise if this warning is normal, or if there might be an issue with my BAM file?
